apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-knowledge-meta-api-dev
spec:
  project: default
  source:
    repoURL: https://gitlab.example.com/group/gitops-repo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: oss-knowledge-backend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
